# Generated by Django 4.1.13 on 2025-12-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
