# Generated by Django 4.1.13 on 2026-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orders_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
